### ISSUE TITLE
"BadRequestError: Must provide query string."

### ISSUE THREAD

**Issue by Xaeed** [jaydenseric/graphql-upload#127]
I've been  trying to post image using curl . we are using `koa-graphql`.
Below is my mutation along with resolvers, but I keep getting error message:

```
error mesage { BadRequestError: Must provide query string.
    at result (/home/**/facade-srv/node_modules/koa-graphql/dist/index.js:121:42)
    at new Promise (<anonymous>)
    at middleware (/home/***/facade-srv/node_modules/koa-graphql/dist/index.js:114:22) message: 'Must provide query string.' }
```

 Mutation:
```js
import { mutationWithClientMutationId } from 'graphql-relay';
import { myContext } from '../../../iam/interfaces';
import { EndpointHandler } from './../../../EndpointHandler';
import { GraphQLUpload } from 'graphql-upload'

export default mutationWithClientMutationId({
    name: 'createFileuploads',
    inputFields: {
        file: {
        type: GraphQLUpload
        

    }},
    mutateAndGetPayload: async ({ file }, ctx: MyContext) => {
      console.log(file);
      const { filename, mimetype, createReadStream } = await file
      const stream = createReadStream();
      console.log('stream data is :',stream);
      // return tryRequest('create', parseResourceList(uploadImage, 'create', 'device_type', ctx), ctx);
    },
    outputFields: EndpointHandler.buildCreateMutationOutput(""),
  });
```
Curl request:

```
curl http://localhost:5000/graphql \
-F operations='{ "query":"mutation ($file: Upload){ createFileUploads(file: $file) }","variables": { "file": null} }' \
-F map='{ "0": ["variables.file"] }' \
-F 0=@/desktop/test.txt
```

Please suggest if I am doing something wrong in my curl reqeust ?

**Comment by jaydenseric** [comment]
Firstly, it looks like the `graphql-upload` middleware has not been setup?

Also, you need to handle the `stream` properly once it's been created. If you don't want to do anything with it yet you can `.destroy()` it, so that the request can continue properly.

A side tip, you probably want to make this change since the file is required input:

```diff
- type: GraphQLUpload
+ type: new GraphQLNonNull(GraphQLUpload)
```

Consider using [`graphql-api-koa`](https://npm.im/graphql-api-koa) instead of [`koa-graphql`](https://npm.im/koa-graphql):

- `graphql-api-koa` is a GraphQL server built from the ground up for a koa environment, allowing you to use nice composable Koa middleware to [catch errors better](https://github.com/jaydenseric/graphql-api-koa#function-errorhandler), etc. whereas `koa-graphql` just wraps `express-graphql`.
- The install size of `graphql-api-koa` [is only 96.5kB](https://packagephobia.now.sh/result?p=graphql-api-koa), wheras `koa-graphql` [is a whopping 3.03MB](https://packagephobia.now.sh/result?p=koa-graphql).
- `graphql-api-koa` is the only GraphQL server to support native ESM in Node.js `--experimental-modules` mode.

**Comment by Xaeed** [comment]
I am getting below 3 error messages after query processing

` query body:
   { query:
      'mutation ($file: Upload!){ createFileuploads(file: $file) }',
     variables: { file: [Promise] } } }
 arugments are:.............. { kind: 'Argument',
  name: { kind: 'Name', value: 'file', loc: { start: 45, end: 49 } },
  value:
   { kind: 'Variable',
     name: { kind: 'Name', value: 'file', loc: [Object] },
`
```
Error ..... { GraphQLError: Field "createFileuploads" of type "createFileuploadsPayload" must have a selection of subfields. Did you mean "createFileuploads { ... }"

Error ..... { GraphQLError: Unknown argument "file" on field "createFileuploads" of type "Mutation".
message :'Unknown argument "file" on field "createFileuploads" of type "Mutation".',

Error ..... { GraphQLError: Field "createFileuploads" argument "input" of type "createFileuploadsInput!" is required but not provided.
message:'Field "createFileuploads" argument "input" of type "createFileuploadsInput!" is required but not provided.',
```

and my Curl request is 
```
curl localhost:5000/graphql  \
-F operations='{ "query": "mutation ($file: Upload!)  { createFileuploads( file : ${file} ) { } }  { , error{code, message} }  }' \
-F map='{ "0": ["variables.file"] }' \
-F 0=@/Desktop/test.txt^C
```

**Comment by jaydenseric** [comment]
Could you please format the code blocks of your posts better? I already formatted your original post for you to try to see better what is going on.

Your cURL request `operations` field does not match the spec. Very obvious errors, like `${file}` and `{ }`.

At this point there is no evidence of a `graphql-upload` bug. If you manage to do everything correctly and still have an issue, we can investigate further :)
