### ISSUE TITLE
Eloquently handle errors outside of a file error 

### ISSUE THREAD

**Issue by ryankauk** [jaydenseric/graphql-upload#138]
I have middleware running with apollo, most simple example is authentication, and if my permissions throw and unauthorized error it cancels the request and the server throws request interrupted. How do I go about allowing these errors to appear through while properly cancelling the upload?

**Comment by ryankauk** [comment]
Dug through a lot of apollo server and graphql upload and tested a bunch, I extended apollo server to self define the applyMiddleware using apollo express and then additionally self defined the upload middleware, in graphql-upload's express middleware I stumbled upon 
```javascript
response.send = (...args) => {
    finished.then(() => {
      response.send = send
      response.send(...args)
    })
  }
```

which I would've assumed would fix the problem, after digging around apollo I found they use the res.write method followed by res.end 

I duplicated this for both these methods and ended up with
```javascript
  const {
        send,
        write,
        end
      } = response
      response.send = (...args) => {
        finished.then(() => {
          response.send = send
          response.send(...args)
        })
      }

      response.write = (...args) => {
        finished.then(() => {
          response.write = write
          response.write(...args)
        })
      }

      response.end = (...args) => {
        finished.then(() => {
          response.end = end
          response.end(...args)
        })
      }
```
and any error thrown before or after processing is returned by the enriched errors as expected.

**Comment by ryankauk** [comment]
Further look into express, it would be better for the libraries code to only replace
```javascript 
response.send = (...args) => {
    finished.then(() => {
        response.send = send
        response.send(...args)
    })
}
```

with
```javascript 
response.end = (...args) => {
    finished.then(() => {
        response.end = end
        response.end(...args)
    })
}
```

send uses end under the hood and will have a more wide coverage

**Comment by mike-marcacci** [comment]
Hi @ryankauk - great job digging through this! I'm the one who added the `response.send` replacement during a large refactor. Its purpose is to ensure the response is not sent until the request is finished, as this breaks HTTP (unless the 100-Continue flow is used).

Just to make sure I'm following, the use case here is that your auth middleware is using `response.write()` and `response.end()` instead of express's `response.send()`, and we don't override those methods.

When I write this, I only overrode `response.send` since it's the idiomatic way to do send a response in express, but as you point out here, many libraries (including this one, actually) are designed to work directly with node's `http` objects.

When I started writing out this reply, I was going to say I am OK overriding these methods, but I'm starting to suspect that since they are part of the `WritableStream` interface, doing this might break the ability of a middleware to actually `.pipe()` a stream to the response object. I'm not sure about this, but I do want to think through how delaying the `.write()`, for example, would effect the firing of events on the `res` stream.

**Comment by ryankauk** [comment]
I'm just using apollo-server with graphql-middleware to verify the access token and then using graphql-shield to check permission. But since these middleware have to direct knowledge that the request is using streams, it might throw and error because the user doesn't have the right permissions for the upload. But apollo-server-express uses the response.write method to send graphql response back to client [here](https://github.com/apollographql/apollo-server/blob/ceee5db460f002a80b837ff0dba1743d4237aaf0/packages/apollo-server-express/src/expressApollo.ts#L48). So in this example an error might be thrown before the resolver is even gotten to, which was sending Request Interrupted on my heroku server.

Yea that's why on my latter I figured end() would be better since it gets called once anyways. Tried looking into it, I don't really have any other ideas, I'm not too knowledgeable about streams. I did find stream.Transform and found an example for throttling the chunks. Maybe that could work? I looked through the node source code and all the event listeners run after the response has been made, I was thinking if you could catch it early enough you could flush the incoming message stream but there doesn't seem to be an outlet for that.

**Comment by mike-marcacci** [comment]
Hi @ryankauk, to circle back on this, I've thought about it a bit more, and decided that this is probably not something we can handle in this package. Streams are very trick business in node, and I feel uncomfortable manipulating the response stream's behavior for what I now believe is actually a flaw in the auth middleware. It isn't precisely a flaw, because HTTP2 and HTTPS _should_ be able to handle multiplexing of the request/response... but in practice this is not implemented in any popular tool, including every major browser, nginx, haproxy, and both Google and AWS load balancers.

As such, any piece of code that directly writes to a [ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse) should first ensure that its [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage) has ended.

Because it is exceedingly common for an HTTP request to fit inside the buffer of network equipment, few authors ever encounter this and an astonishing amount of node apps and packages (including some that I have written) naively send HTTP responses that are broken depending on the request size and the configuration of intermediary network equipment.  I definitely would _like_ the ability to send an early HTTP response, but after dozens and dozens of hours comparing the specs and the most popular implementations, it appears that in practice this is simply not possible.

This is the safe<sup>1</sup> way to send an early response:
```js
function send(data): void {
  if (request.complete) {
    response.end(data);
  } else {
    request.on("end", () => response.end(data));
    request.resume();
  }
}
```

If you wish to open issues for the other projects in your stack (such as `graphql-shield`) feel free to reference this issue, and I will be more than happy to explain the situation to them in detail

---


<sup>1</sup> This is "safe" from the perspective of "sending a valid response." However, there are times – such as mitigating malicious traffic – when you _want_ to drop the request to keep it from using network resources. In that case, the "safe" thing to do is to immediately close the request and not worry about responding.
