### ISSUE TITLE
Finish triggered twice, once with undefined operations

### ISSUE THREAD

**Issue by NGPixel** [jaydenseric/graphql-upload#141]
Using Node.js **v10.15.3** on Ubuntu **18.04.2 LTS**

I'm getting the error `BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).`

At first it looked like a middleware messing with the body, but after further debugging, the `operations` field is present and placing graphql-upload as the first middleware results in the same issue.

Adding a few console.log in the `processRequest.js` file reveals that the `operations` field is found and parsed correctly. However, the `finish` event is called twice; once with an undefined `operations` and a second time with the proper value:

```
FIELD operations { operationName: null,
  variables: { data: null },
  extensions: {},
  query:
   'mutation ($file: Upload!) {\n  assets {\n    upload(data: $file) {\n      responseResult {\n        succeeded\n        message\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n' }
FIELD map {"1":["variables.data"]}

FINISH operations undefined
[ { BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
    message:
     'Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).',
    locations: undefined,
    path: undefined,
    extensions: { code: 'INTERNAL_SERVER_ERROR' } } ]

FINISH operations { operationName: null,
  variables: { data: Promise {
     { filename: 'artwork.jpg',
       mimetype: 'image/jpeg',
       encoding: '7bit',
       createReadStream: [Function: createReadStream] } } } },
  extensions: {},
  query:
   'mutation ($file: Upload!) {\n  assets {\n    upload(data: $file) {\n      responseResult {\n        succeeded\n        message\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n' }
```

Any idea what could be causing this?

Thanks!

**Comment by mike-marcacci** [comment]
Hmm, this is indeed weird behavior. Given that this library never actually emits a `finish` event, I do suspect that your initial idea is correct: another middleware might be directly manipulating the request stream. Because streams are processed asynchronously, it likely doesn't matter that the middleware order was switched – child middleware will be called (and can fire off a stray `finish` event) as soon as the `map` field is parsed.

One thing to note here is that in order for a stream to be split to multiple consumers and provide the same exact content to all of them, them must all be attached synchronously, and in the same js event frame. In other words, a consumer that's attached to a partially-consumed stream will only receive the remaining data.

If you *do* have a use case that requires a stream to be forked like this (which is unlikely), you'll have to create your own koa/express middleware and directly call graphql-upload's [`processRequest()`](https://github.com/jaydenseric/graphql-upload#function-processrequest) with the relevant streams.

Either way, I'd first try removing the other middleware to see if you can reproduce the problem with this library on its own. More generally, look for anything else that might be working directly with the request stream; this is probably the culprit.

Hope that helps, and best luck tracking this down!

**Comment by nightire** [comment]
I'm facing the same problem by using apollo-server-koa in project strapi, here is the related issue:

https://github.com/strapi/strapi/issues/2558

**Comment by mike-marcacci** [comment]
@NGPixel @nightire what other middleware is running in your specific configurations – and are these both using koa, or is your case with express @NGPixel?

**Comment by mike-marcacci** [comment]
Also @nightire what specific node version are you running?

**Comment by nightire** [comment]
> @NGPixel @nightire what other middleware is running in your specific configurations – and are these both using koa, or is your case with express @NGPixel?

I'm not sure, I'm using an open-source API service framework called [strapi](https://github.com/strapi/strapi), not sure its middleware stacks, but only know it uses apollo-server-koa which depends on graphql-upload.

I've tried to debug this issue, by the time the `finish` event got triggered, I noticed there are two listeners in my case, and the one from graphql-upload is the very first one.

Node version: v10.15.3

**Comment by mike-marcacci** [comment]
@nightire - I believe the strapi issue referenced above is different; it appears that their front-end is simply not sending a multipart request. Since we haven't heard back from @NGPixel I'm going to go ahead and close this issue, as I suspect the problem is with of-yet unnamed 3rd party middleware.
