### ISSUE TITLE
‘Upload’ scalar serialization unsupported.

### ISSUE THREAD

**Issue by TrillCyborg** [jaydenseric/graphql-upload#144]
I'm getting this error which I see is coming from `serialize()` but I have no idea what is calling this function or why.

I am using `apollo-server` with `makeExecutableSchema` and `type-graphql` for setting up resolvers and schema.

**Comment by jaydenseric** [comment]
The `Upload` scalar can't be serialized to a string, because it represents a binary file in various states of being streamed. Fortunately there is no reason to serialize such a scalar.

I don't know why something in your setup is attempting to serialize it; I doubt the problem is caused by a bug here.

**Comment by jaydenseric** [comment]
It seems this issue doesn't relate to a bug in this repo, but feel free to report back here for the benefit of others if you manage to solve the problem :)
