### ISSUE TITLE
Race condition when opening read capacitor before write capacitor is ready. 

### ISSUE THREAD

**Issue by gregory** [jaydenseric/graphql-upload#167]
The doc in fs-capacitor might be misleading, but [creating a WriteStream](https://github.com/jaydenseric/graphql-upload/blob/master/src/processRequest.mjs#L305) is actually [asynchronous](https://github.com/mike-marcacci/fs-capacitor/blob/v2.0.4/src/index.mjs#L142). 

Because we call [upload.resolve(file)](https://github.com/jaydenseric/graphql-upload/blob/master/src/processRequest.mjs#L351) before the fd is actually open, this could lead to issues like the one opened in [fs-capacitor](https://github.com/mike-marcacci/fs-capacitor/issues/18), where [path is set to an empty string](https://github.com/mike-marcacci/fs-capacitor/blob/v2.0.4/src/index.mjs#L77).

**Comment by mike-marcacci** [comment]
Hi @gregory, I just re-read this and the [referenced issue in fs-capacitor](https://github.com/mike-marcacci/fs-capacitor/issues/18) and I just want to clarify something:

I don't think that you're describing a "race condition" anywhere, but instead that you expect the `stream.path` to be present immediately when the field resolves. The `fs-capacitor` library is not really designed to have apps access the file directly (or care about it at all), which is why the path field was never documented.

In the newest versions of `fs-capacitor`, the `path` field has been renamed to `_path` to make it more clear that it is simply an implementation detail. I'm fairly certain that you _don't_ want to access it, and the linked issue is a perfect example: the `form-data` library is trying to use this path to make inferences about the file size and its type, _neither_ of which will be correct.

I'm going to go ahead and close this issue and the associated PR, since that entire field is going away. If I misinterpreted your scenario and you're actually describing a race condition involving the streaming data, please let me know and I'll reopen these!

**Comment by gregory** [comment]
hello @mike-marcacci thanks for looking into this! 

I might have not being clear enough, but there are actually two issues.

Upon opening a write stream, fs-capacitor is using [fs.open to create a file.](https://github.com/mike-marcacci/fs-capacitor/blob/v2.0.4/src/index.mjs#L130) and that call is async. 

I haven't been able to find where you were waiting for the file to be created before exposing the [file. createReadStream](https://github.com/jaydenseric/graphql-upload/blob/master/src/processRequest.mjs#L341) function, which 
would allow someone to open a read stream on a file that doesn't exists yet or [erroring](https://github.com/mike-marcacci/fs-capacitor/blob/v2.0.4/src/index.mjs#L131). 

Doing so is only leading to the .path issue, where [this.path get set to an undefined string](https://github.com/mike-marcacci/fs-capacitor/blob/v2.0.4/src/index.mjs#L77) 

I'll move the discussion to form-data/form-data#394 to avoid further confusions.

**Comment by mike-marcacci** [comment]
@gregory - thank you so much for your clarification here. The reason that there is not a race condition is that the `.path` field is _not_ intended to be used outside the `fs-capacitor` library (and is actually renamed to `._path` in the most recent versions to make this more clear).

The reason there is no race condition is that the _read_ stream waits until the _write_ stream is ready before it begins returning data: https://github.com/mike-marcacci/fs-capacitor/blob/c12ceb198c443af836a7e1ba025c1619ba63d7c8/src/index.ts#L46-L49

Let me know if you still see a race condition here.
