### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RyannGalea** [jaydenseric/graphql-upload#173]
Update the FileUpload Scalar to include total file size in bytes?

```
export interface FileUpload {
  filename: string;
  filesize: number;
  mimetype: string;
  encoding: string;
  createReadStream(): ReadStream;
}
```

**Comment by jaydenseric** [comment]
Because the content is streaming in via a multipart request, there is no way to know what the individual file sizes are until they have been fully uploaded. Even if there was a convenient way for the client to signal the file sizes, it couldn't be trusted.

There is a [`maxFileSize`](https://github.com/jaydenseric/graphql-upload#type-processrequestoptions) option if you only care about limiting the file size, or you can measure the size of the streams yourself in resolvers.

See previous discussion about this here: https://github.com/jaydenseric/graphql-upload/issues/30.
