### ISSUE TITLE
Is it possible to limit the total file size?

### ISSUE THREAD

**Issue by juona** [jaydenseric/graphql-upload#188]
Hi there, me again!

I was wondering if there was a way to limit the total upload size? I would assume implementing something like this is troublesome in graphql-upload since you are processing multiple streams independently, but perhaps I am wrong. Thought I'd ask for thoughts/advice, since surely you have thought about this too.

Related: https://github.com/jaydenseric/graphql-upload/issues/30.

OT: say I am uploading a number of files and only one of them is too large. Will other uploads succeed or will they be cancelled? Or is the behaviour undefined?

**Comment by mike-marcacci** [comment]
We don't currently have a mechanism for limiting the total request size, although I'm sure we would be open to a PR that added it.

While this package's streams allow the uploads to be accessed in any order (thanks to some clever concurrent filesystem buffering) the actual HTTP request is a single stream of bytes. When a file exceeds the `maxFileSize`, we continue to read the request, but instead of writing its contents to disk, we just discard the bytes. This means that files appearing in the HTTP stream both before and after continue to work.

A similar approach _could_ be applied to "total request size" but in which the contents of the offending file and all subsequent files are discarded. This would still process the entire HTTP request, but would limit the amount of size a single request could buffer to disk.

While this would be a good addition in situations where temp disk space is scarce, the most common reason for this kind of limit is to prevent network abuse, which wouldn't be addressed by this strategy since the bytes are still read over the network. To prevent this, the normal approach is to abort the connection, which would typically be done at a load balancer level, resulting in no response making its way to the client.

**Comment by jaydenseric** [comment]
I concur with @mike-marcacci. Users can limit the total size of the request via their server config or other middleware. Closing, but anyone else feel free to chime in!

**Comment by juona** [comment]
A great answer/explanation by @mike-marcacci, once again! I'm sorry I did not thank for it - I guess my focus wandered somewhere else and I forgot about it. Just got an email about the closing of the issue - and yes, I think it's reasonable.

Thanks once again, guys!
