### ISSUE TITLE
graphqlUploadKoa must be loaded after Apollo 2.0 applyMiddleware call?

### ISSUE THREAD

**Issue by njg-nf** [jaydenseric/graphql-upload#192]
Otherwise graphql-upload tries to process *all* GraphQL requests for me. Posting issue as this is inconsistent with the documentation here:

> Use the graphqlUploadKoa or graphqlUploadExpress middleware just *before* GraphQL middleware

**Comment by mike-marcacci** [comment]
This package will process all middleware that is sent with a Content-Type of `multipart/form-data` according to the [GraphQL Multipart Request Spec](https://github.com/jaydenseric/graphql-multipart-request-spec) but will _not_ process those with another Content-Type, like `application/json`.

FWIW you're probably running into issues because Apollo itself uses this package to provide upload support, and so you're likely trying to process the multipart request twice.

The documented behavior is correct – this must be applied before any GraphQL-consuming middleware to have any effect.

**Comment by njg-nf** [comment]
> FWIW you're probably running into issues because Apollo itself uses this package to provide upload support, and so you're likely trying to process the multipart request twice.
That does seem to have been the issue; I somehow was under the impression that this package was still necessary for file upload support when running Apollo.
