### ISSUE TITLE
Upgrade graphql to ^15.1.0

### ISSUE THREAD

**Issue by mkorablin** [jaydenseric/graphql-upload#215]
Hello,

Would you mind releasing a new version with graphql dependency bump to ^15.1.0? Signature for `GraphQLScalarType` [was changed in 15.1.0](https://github.com/graphql/graphql-js/pull/2276) and currently peer dependency declaration results in conflict.

Here are [release notes for 15.1.0](https://github.com/graphql/graphql-js/releases/tag/v15.1.0)

Thank you! 🙇

**Comment by jaydenseric** [comment]
I'm a little confused about what you are requesting; our current peer dependency version range for `graphql` already includes v15.1.0:

https://github.com/jaydenseric/graphql-upload/blob/a3b7b31406aa47567ced0b60eea1cd764db8932c/package.json#L44-L46

If you do a fresh install of `graphql` and `graphql-upload` in a project (or update your dependencies in an existing project), it should work.

<img width="897" alt="Screen Shot 2020-08-18 at 2 01 54 pm" src="https://user-images.githubusercontent.com/1754873/90469176-72a65b80-e15b-11ea-86c7-f45a75bbbff1.png">

**Comment by Daavidaviid** [comment]
I encountered the same issue

**Comment by mkorablin** [comment]
@jaydenseric peer dependency allows to install @graphql@15.1.0. However your own library depends on graphql@15.0.0 and your definition for `GraphQLUpload` uses `GraphQLScalarType` from version 15.0.0 This results in conflict when trying to pass `GraphQLUpload` to resolvers that expect `GraphQLScalarType` that matches version 15.1.0.

In short, your peer dependency is only until 15.0.0 and 15.1.0 breaks, the change in 15.1.0 in graphql library wasn't backwards compatible.

**Comment by Daavidaviid** [comment]
How would one solve this quickly ? Increasing the peerdependency version number is enough you think ?

**Comment by jaydenseric** [comment]
`graphql` is unlikely to publish a breaking change in a minor release in violation of semver, but to be sure everything works with the latest version I updated the dev dependencies and ran all the tests successfully.

@mkorablin 

> However your own library depends on graphql@15.0.0

Perhaps you're confused. My library (I guess you were referring to `graphql-upload`?) only has a `graphql` peer dependency, it's not a `dependency`; see for yourself:

https://unpkg.com/graphql-upload@11.0.0/package.json

@Daavidaviid

> How would one solve this quickly

You don't wan't multiple versions of `graphql` in your `node_modules`, so best thing to do is to run `npm outdated`, then update all your dependencies, then delete your `package-lock.json`, do a fresh `npm install` to deeply install the most up to date packages as possible, then run `npm ls graphql` to list all the versions of `graphql` installed, and what package is installing them.

Probably your project dependencies just need updating, but if a third party package is pulling in an older version of `graphql` (normally that happens when they "pin" dependencies by not using `^`, a big antipattern) you need to figure out if a newer version of that package is available that doesn't have the problem, or else raise an issue/PR to fix it.

Most packages in the `graphql` ecosystem have `graphql` as a peer dependency (instead of a regular dependency) specifically to avoid the multiple version headaches you're apparently experiencing; your project's `package.json` should be the source of truth with a particular `graphql` version as a dependency.

**Comment by Daavidaviid** [comment]
My issue was linked to https://github.com/jaydenseric/graphql-upload/issues/214
