### ISSUE TITLE
Error: Network error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Eriickson** [jaydenseric/graphql-upload#217]
Hola, estaba utilizando apollo-server y todo me funcionan de maravilla, el problema es ahora que quiero migrar a apollo-server-express, ya que cuando lo intento el Frontend de React me arroja un error "Error: Network error: Unexpected token < in JSON at position 0"
apollo-server:
![image](https://user-images.githubusercontent.com/38663299/94433868-ed08c900-0166-11eb-83e1-b1b69e93fdee.png)

apollo-server-express: 
![image](https://user-images.githubusercontent.com/38663299/94433963-0a3d9780-0167-11eb-8b9e-eef7afa36633.png)

react error: 
![image](https://user-images.githubusercontent.com/38663299/94434056-32c59180-0167-11eb-933c-391fbe553850.png)

**Comment by jaydenseric** [comment]
What evidence is there that your problem relates to `graphql-upload`? It seems you need help to debug the behavior of `apollo-server-express`? That package is maintained by Apollo, not me.

Feel free to report back here what your problem was for the sake of future googlers :) Of course, if you manage to narrow down a bug in one of the packages I maintain we can either reopen the issue here, or if the problem relates to another package you can raise an new issue in the relevant repo.
