### ISSUE TITLE
Invalid JSON in the ‘operations’ multipart field when upload formdata?

### ISSUE THREAD

**Issue by siamahnaf198** [jaydenseric/graphql-upload#270]
I can't say that is it issue or my code problem. I am trying to upload file from next js application. I create a formdata. But I get an error like this-
![Screenshot 2021-10-18 132322](https://user-images.githubusercontent.com/78312010/137775169-3fd33841-af9e-4c52-8ecf-960e411ffbc6.png)

Here is my requst function code-
```
formData.append('operations', '{ "query": "mutation($file: Upload!) {signUp(avatar: $file, input: {name: \"Siam Ahnaf\", email: \"siamahnaf198@yahoo.com\", password: \"siam1980\"}){message, token}}", "variables": { "file": null } }');
    formData.append('map', '{ "0": ["variables.file"] }');
    formData.append('0', Image);

    await axios.post("http://localhost:3001/graphql", formData, {
        headers: {
            'Content-Type': 'application/json'
        }
    })
        .then(response => console.log(response))
        .catch(error => console.log(error));
```

I can't understand where is the problem or the issue. Please anyone help me.

But in apollo studio it runs or uploads file successfully. Here is the image-
![Screenshot 2021-10-18 131758](https://user-images.githubusercontent.com/78312010/137775420-ade4a010-3b3a-4807-bf65-5b08c4fbe6f2.png)

Can you help me. Please!

Note***- My backend and frontend application both are running in localhost ( obviously different port ).

**Comment by jaydenseric** [comment]
@siamahnaf198 you are now blocked across every repo I maintain for spamming various repos for help with your work.

- I politely asked you not to raise issues asking for help with your work, and even gave you a few tips to help you solve your problem: https://github.com/jaydenseric/graphql-multipart-request-spec/issues/57#issuecomment-943114969
- You then raised another issue in the same repo begging for help again after I closed the first one. Although you were testing my patience and had insulted me by saying ["I think you are very angry person"](https://github.com/jaydenseric/graphql-multipart-request-spec/issues/57#issuecomment-943597794), I kindly explained the silly mistakes you were making with invalid JSON (and should have been able to figure out on your own easily without bothering the [15 repo watchers](https://github.com/jaydenseric/graphql-multipart-request-spec/watchers) who get email notifications about every issue and comment): https://github.com/jaydenseric/graphql-multipart-request-spec/issues/58#issuecomment-945446875 . You then made another 2 comments spamming for help, and revealed you are still writing invalid JSON with incorrect escapes: https://github.com/jaydenseric/graphql-multipart-request-spec/issues/58#issuecomment-945452214 .
   
   <img width="168" alt="Screen Shot 2021-10-19 at 1 08 41 pm" src="https://user-images.githubusercontent.com/1754873/137832029-7c7555d2-abb4-4bdc-8c53-bc6484931961.png">
- Now you raise another issue here begging for help again: https://github.com/jaydenseric/graphql-upload/issues/270 . The fact that GraphQL multipart requests for the same operation made by tools and not your own hands work fine prove the issue is not a problem with `graphql-upload`, yet you raise an issue here anyway and bother [13 watchers](https://github.com/jaydenseric/graphql-upload/watchers). Use the network inspector to compare character by character a successful correct request, with whatever incorrect request you are manually sending. Pay attention to detail.

I almost _never_ block users or lock issues, but I can't allow you to continue disturbing repo watchers with frivolous issues after I politely asked you not to. These GraphQL upload related packages are well documented and are installed millions of times per week; no one else is having trouble and begging for help all the time. Only you. Please reflect on this.

Use StackOverflow or some group chat for JS/GraphQL help if you are still stuck.
