### ISSUE TITLE
Error: A ReadStream cannot be created from a destroyed WriteStream.

### ISSUE THREAD

**Issue by Froctnow** [jaydenseric/graphql-upload#283]
Hello, I have a resolver that receives files as input. Waiting for them to be received, then I try to create a stream, but I get an error: Error: A ReadStream cannot be created from a destroyed WriteStream.
Resolver and function below.
I am definitely not sending a response, the error falls exactly at the moment the createReadStream function is called.

```
  @UseGuards(AuthGuard)
  @Mutation(() => LocationEntity)
  async createLocation(
    @Args("createLocationData") createLocationData: LocationCreateInputModel,
    @Args({ name: "fileList", type: () => [GraphQLUpload] }) fileList: Promise<FileUpload>[],
    @CurrentUser() user: UserJwtDto,
  ) {
    const files = await this.locationService.waitUploadFiles(fileList);

    files[0].createReadStream();

    return await this.locationService.create(createLocationData, user.id, files);
  }
```

```
  async waitUploadFiles(fileList: Promise<FileUpload>[]) {
    const files: FileUpload[] = [];

    await doInParallel(fileList, file => file.then(res => files.push(res)));

    for (const file of files) {
      if (!["image/png", "image/webp", "image/jpeg"].includes(file.mimetype))
        throw new HttpException("Format file doesn't support. Use png, webp, jpeg", HttpStatus.BAD_REQUEST);
    }

    return files;
  }
```

**Comment by jaydenseric** [comment]
For issues like this, please share your Node.js and `graphql-upload` versions.

I'm confused by the logic in that resolver. You shouldn't await the promises to resolve for all files, then after attempt to read the stream of the first. Because files resolve and stream one at a time, one after another.

See in the multiple uploads example how the entire processing of each uploading, including awaiting it's promise then promisifying the stream, happens in isolation:

- https://github.com/jaydenseric/apollo-upload-examples/blob/e1131d21b54d66391da342fb81981e805b857c8a/api/schema/MutationType.mjs#L31
- https://github.com/jaydenseric/apollo-upload-examples/blob/e1131d21b54d66391da342fb81981e805b857c8a/api/storeUpload.mjs#L5-L42

**Comment by Froctnow** [comment]
I figured out the error, the problem was that the service was brought up under a user who does not have access to the file when you process it in proccessRequest.
I don't get any error from the library about this, and the object becomes "destroyed".
I don’t know how to test and catch this, I hope no one will encounter this.

**Comment by sgentile** [comment]
I get this when the filesystem is set to readonly
