### ISSUE TITLE
issue with video upload

### ISSUE THREAD

**Issue by sushilbansal** [jaydenseric/graphql-upload#288]
Image upload works fine from both web and mobile. Video upload works fine from mobile but fails on web.

Demo link: https://www.tryhelpline.com (check the network/console tab when you upload a video)

Repo for backend: https://github.com/sushilbansal/TempSpeakPrepServer
Repo for frontend: https://github.com/sushilbansal/TempSpeakPrepNext

Please let me know if you need any other info on my end. Thanks a lot :)

**Comment by jaydenseric** [comment]
There is a `net::ERR_FAILED 413`, and HTTP status code 413 "Payload Too Large" indicates your server (e.g. nginx) has too small request/file upload limits configured to upload a video which is probably larger than other kinds of files you've tried. Your server config should be looser that the `graphql-upload` configured limits so that `graphql-upload` can do a nicer GraphQL response with relevant errors.

**Comment by sushilbansal** [comment]
Thanks for helping out @jaydenseric . Really appreciate that; it helped me in narrowing down the issue and eventually resolving it. Have a nice day.
