### ISSUE TITLE
Can't upload on Nest.js

### ISSUE THREAD

**Issue by Sydwelll** [jaydenseric/graphql-upload#301]
Here is my mutation :

```
@Mutation(() => Boolean)
  async uploadProfilePicture(
    @Args('attachment', { type: () => GraphQLUpload }) attachment: FileUpload,
  ) {
    await this.uploadService.uploadPublicFile(attachment);
  }

```  
  Here is my GraphQLModule configuration :
  
  ```
GraphQLModule.forRootAsync<ApolloDriverConfig>({
          driver: ApolloDriver,
          imports: [ConfigModule],
          inject: [ConfigService],
          useFactory: (configService: ConfigService) => {
            return {
              .....
              uploads: false,
              path: '/graphql',
              ....
```

and in my AppModule i added : 

```
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(graphqlUploadExpress()).forRoutes('graphql');
  }
}
```
Here's my `package.json`

```
....
"@nestjs/graphql": "^10.0.8",
"apollo-server-express": "^3.6.7",
"graphql": "^15",
"graphql-upload": "^13.0.0",
......
```

And i'm getting this error : (i tried with my Next.js frontend and Postman)

`Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).`

**Comment by jaydenseric** [comment]
I'm not a Nest.js user so it's better to ask the Nest.js community for help with Nest.js.

In this case though, maybe the error is legit? Maybe the problem is the front end is not sending a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure) due to the missing multipart field `operations`.
