### ISSUE TITLE
Type mismatch errors internal to graphql-upload

### ISSUE THREAD

**Issue by markgreenwood** [jaydenseric/graphql-upload#323]
I have followed the advice elsewhere about importing correctly from `graphql-upload` and using the recommended settings in `tsconfig.json`, but I'm still getting type errors that seem to be internal to `graphql-upload` and its dependencies:

```
> tsc

node_modules/graphql-upload/processRequest.js:272:47 - error TS2345: Argument of type 'FileUploadCreateReadStreamOptions' is not assignable to parameter of type 'string'.

272             return capacitor.createReadStream(options);
                                                  ~~~~~~~

node_modules/graphql-upload/processRequest.js:332:35 - error TS2339: Property 'release' does not exist on type 'WriteStream'.

332             upload.file.capacitor.release();
                                      ~~~~~~~


Found 2 errors in the same file, starting at: node_modules/graphql-upload/processRequest.js:272
```

**Comment by jaydenseric** [comment]
Perhaps the version or types for the dependency `fs-capacitor` is incorrect? Also, do you have `@types/node` installed, at the right version?

I can't really debug the problem for you because you need to try to figure out where those types are coming from, etc. in your project.

**Comment by jaydenseric** [comment]
@markgreenwood The problem is likely that you incorrectly have `@types/graphql-upload` installed in your project, and as @uragecz pointed out those types pull in `@types/fs-capacitor` which are outdated:

https://unpkg.com/browse/@types/graphql-upload@8.0.11/package.json

Recent versions of `graphql-upload` have built in types via TypeScript JSDoc comments, so you should uninstall `@types/graphql-upload` from your project. If it's not you that installed it, but one of your dependencies, you can track down where it's coming from by running `npm ls @types/graphql-upload`.
