### ISSUE TITLE
No "exports" main defined "\node_modules\graphql-upload\package.json"

### ISSUE THREAD

**Issue by nekmart** [jaydenseric/graphql-upload#333]
Hello, I am building a nestjs project with typescript and graphql. I want to use graphql-upload in my project.

I install two package-
1. `graphql-upload`
2. `@types/graphql-upload`

After installing this packages. I import it-

`import { GraphQLUpload, FileUpload } from "graphql-upload";`

And my Mutation-
```
@Mutation(() => SuccessInfo, { name: "addBrand" })
@Roles(Role.MODERATOR, Role.ADMIN)
@UseGuards(AuthGuard, RolesGuard)
add(
    @Args("brandInput") brandInput: BrandInput,
    @Args('file', { type: () => GraphQLUpload }) file: FileUpload,
) {
    return this.brandService.add(brandInput);
}
```

Here I am getting this error-
![Screenshot 2022-08-25 225447](https://user-images.githubusercontent.com/111189053/186726420-6b1bee06-d19f-4944-b2b9-de249ba46db0.png)

I see this issue alreay- https://github.com/jaydenseric/graphql-upload/issues/305

From this issue I am trying to use-

`import GraphQLUpload from "graphql-upload/GraphQLUpload.js";`

But here I am getting typescript type declaration error like this image-
![Screenshot (5)](https://user-images.githubusercontent.com/111189053/186726869-751450f4-1666-48c9-a9b1-9c733bfa42d6.png)

How can I solve this issue.

**Comment by jaydenseric** [comment]
In the readme exports section:

https://github.com/jaydenseric/graphql-upload#exports

<img width="799" alt="Screen Shot 2022-08-26 at 8 01 48 am" src="https://user-images.githubusercontent.com/1754873/186776793-b0cb7887-cb0a-4b6c-8c84-d2f68fcd806e.png">

You can see the module is documented as `GraphQLUpload.mjs`.

If you just look at the modules that are published:

https://unpkg.com/browse/graphql-upload@16.0.1/

<img width="947" alt="Screen Shot 2022-08-26 at 8 03 01 am" src="https://user-images.githubusercontent.com/1754873/186777126-513b2935-ae99-4658-967a-6c8226830561.png">

You can see the module really is called `GraphQLUpload.mjs`.

So why are you attempting this, with `.js` instead of the correct `.mjs`?

```js
import GraphQLUpload from "graphql-upload/GraphQLUpload.js";
```

Even if you were importing correctly, it seems Nest.js doesn't support importing standard JavaScript modules anyway so you will probably run into that soon, see https://github.com/jaydenseric/graphql-upload/issues/332#issuecomment-1223003793 . If you do run into that issue, please raise it with Nest.js not here.
