### ISSUE TITLE
support default tsconfig compilerOptions.module

### ISSUE THREAD

**Issue by revero-doug** [jaydenseric/graphql-upload#351]
an optimal module configuration in a public library promotes interoperability over all other concerns. please consider updating the library to maximize compatibility with typical tsconfig settings.

**Comment by jaydenseric** [comment]
Firstly, there is no "default" TypeScript config.

It seems you are asking this library to configure `compilerOptions.module` to the legacy `"node"` option (instead of using the `"nodenext"` option that superseded it) which isn't capable of resolving standard Node.js packages using stable Node.js LTS features like the package `exports` and `type` fields, or ESM and CJS interop via the `.mjs` file extension, etc. This is not a viable suggestion, because this package uses a lot of those things, and needs to resolve and process other modern Node.js packages correctly too.

> a public library promotes interoperability over all other concerns

That is why all my open source projects have moved to standard ESM module format, and the most current TypeScript config for compatibility with the current Node.js API. In time, we won't need to care about legacy CJS interoperability concerns and it will all just be a bad memory like legacy IE is. To get there, library authors like me have to make the first moves or it will never happen. Fortunately, lots of other authors are making the same moves and have migrated their packages over to pure ESM.

**Comment by jaydenseric** [comment]
You seem to have a very narrow definition of "interoperability" that means compatibility with your specific legacy TypeScript Node.js CJS setup. CJS is completely not operable in browsers; ESM is. There are other ESM only runtimes as well. My packages are all moving to be standard JavaScript modules that work in any standard JavaScript runtime. I have real websites up and running that the full back and front end is running on pure ESM without even a build step, using https://ruck.tech (for a list, see https://github.com/jaydenseric/ruck#examples). I couldn't have built the Ruck framework or buildless websites if my packages were not pure ESM; so yes there is real practical value in doing it not just to "push a highly opinionated stance". How can using standard JavaScript be "opinionated" lol.

**Comment by jaydenseric** [comment]
To better explain what I meant by there being no default TypeScript config, what I meant is there is not just __*ONE*__ TypeScript default config. Deno has it's own default config, tsc in Node.js has it's own default config, etc. etc. Configuring module resolution to `nodenext` actually aligns with the Deno behavior, because you need to enforce file extensions in import paths. I've deeply considered (and tested) compatibility across runtimes and type checkers when choosing my open source TypeScript config.

At some point, I will swap out the Node-isms in this package, and it will work for Deno too, as well as any other runtimes that provide standard web APIs. It's a long term vision that could suddenly become a short term one if I have to build a Deno GraphQL API with file uploads.

**Comment by jaydenseric** [comment]
I'm using this library at work right now in an enterprise Node.js TypeScript project just fine. If you are having TypeScript errors with Apollo projects, raise issues there, not here.

My package does exactly what it says in the readme; nothing you are complaining about is a bug. Everything is functioning as meticulously designed. You just disagree with my vision. Well, it's not your project and I'm allowed to have a vision. You're not paying for it, and it seems you're not even a user of it yet you are trying to bully us to completely change the direction of the project. You've expressed your opinions (which are not unique to past discussions), I'm really busy today with work so I can't afford a lengthy back and forth on this.
