### ISSUE TITLE
Unexpected end of form at Multipart._final

### ISSUE THREAD

**Issue by albertshinBFG** [jaydenseric/graphql-upload#362]
Greetings!

Any help here would be appreciated...
Super strange issue here. I have a React/Node.js application paired with Apollo GraphQL and Express.
I've implemented `graphql-upload` in addition to `apollo-upload-client` in the frontend to be able to upload files such as CSVs to Google Cloud Storage.

When developing locally, everything works just fine. I'm able to select the file to upload and stream it up to GCS.

However, once I deployed my changes via Google Cloud Run, I started getting this error:
```
Error: Unexpected end of form
    at Multipart._final (/usr/src/app/node_modules/busboy/lib/types/multipart.js:588:17)
    at callFinal (internal/streams/writable.js:610:10)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

This error is only occurring when deployed on GCP.
Any ideas as to why this could be happening?

Node Version: 14.20.1
apollo-upload-client: ^17.0.0
graphql-upload: ^16.0.2
apollo-server-express: ~2.14.3
express: ~4.17.1
graphql: ~15.5.0

**Comment by albertshinBFG** [comment]
@jaydenseric @mike-marcacci

**Comment by jaydenseric** [comment]
I'm not familiar with Google Cloud Run, but maybe this issue is relevant:

https://github.com/jaydenseric/graphql-upload/issues/129

This comment generally applies for both the Google Cloud Functions and AWS Lambda issues:

https://github.com/jaydenseric/graphql-upload/issues/155#issuecomment-632998596

Just googling quickly, it seems Google Cloud run has a request size limit of 32 MB:

https://cloud.google.com/run/quotas

So, maybe it's cutting your requests off early if you are exceeding that?

**Comment by albertshinBFG** [comment]
Hey @jaydenseric 
I appreciate the response!

So I tried to replace `graphql-upload` with `graphql-upload-minimal` and unfortunately I'm still running into the same exact error:

`<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Error: Unexpected end of form<br> &nbsp; &nbsp;at Multipart._final (/usr/src/app/node_modules/busboy/lib/types/multipart.js:588:17)<br> &nbsp; &nbsp;at callFinal (internal/streams/writable.js:610:10)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:82:21)</pre>\n</body>\n</html>\n"`

Apologies for the raw paste but you'll see
`Error: Unexpected end of form at Multipart._final (/usr/src/app/node_modules/busboy/lib/types/multipart.js:588:17) at callFinal...`

In response to your search related to the request size, I'm definitely not going over the size limit as the file is only 450 bytes.

In addition, the error is occurring long before the actual uploading to google and instead is happening even before it hits my resolver.

Super strange behavior as `graphql-upload` & `graphql-upload-minimal` paired with `apollo-upload-client` works perfectly when I try locally. But only when the app is deployed to GCP does it error with the Unexpected end of Form.

I'm not very experienced with the whole mix of using GraphQL/Express and Multipart form content types; Any other leads? Do you think maybe i should try replacing `apollo-upload-client` with a different package?

**Comment by albertshinBFG** [comment]
Hey @jaydenseric Thank you for your response!

I should clarify my problem as I'm more clear as to what may be going wrong.

I have two express servers. The first one intercepts all requests from the Frontend prior to passing the request to the backend.

Locally, this first express server isn't in use and is only in use when deployed. This is where the issue is happening and hence the difference between local and deployed.

The issue is definitely happening in this client-side express server as I have graphqlUpload implemented in my backend server and without the client-side one this whole flow works perfectly.

**How do you suggest passing this multipart form from one express server to another?**

 I've tried to use graphqlUploadExpress middleware in my client-side express server but it still doesn't work. Do I have to use multer here?

**Comment by jaydenseric** [comment]
The problem of forwarding a GraphQL multipart request (or just part of a request) from one server to another is a well known, and in many cases  a solved, problem that's particularly relevant for federated GraphQL API proxies/gateways that stitch together over HTTP multiple GraphQL APIs. This issue for example relates to that: https://github.com/jaydenseric/graphql-upload/issues/194 .

In your case, you might not need to do anything particularly complicated if you don't need to deconstruct the GraphQL request and only forward parts of it to other servers responsible for fulfilling those individual parts; you might be able to somehow pass through the entire multipart request stream without much effort. It's not something I've done before though, so I'm not sure exactly the best way to tackle it.

Helping out further with this is really beyond the scope of maintaining this package because it's more about setting up your particular server infrastructure. Feel free to share the final solution you come up with here, in case it helps others with a similar question.

**Comment by bilabror** [comment]
I'm dealing with this issue; how did you resolve it?
