### ISSUE TITLE
Error: No "exports" main defined in /Volumes/Personal/code-work/node-projects/office/pf-node-backend/node_modules/graphql-upload/package.json

### ISSUE THREAD

**Issue by aoneahsan** [jaydenseric/graphql-upload#371]
Error: No "exports" main defined in /Volumes/Personal/code-work/node-projects/office/pf-node-backend/node_modules/graphql-upload/package.json

I just updated the "graphql-upload" and other packages versions in my node project and now when I tried to run it it's giving this error

<img width="1500" alt="Screenshot 2023-05-26 at 10 54 27 PM" src="https://github.com/jaydenseric/graphql-upload/assets/37369204/254ee905-d49e-40e9-b131-68dd759a83e2">

here is what my old package.json file was before this update
<img width="389" alt="Screenshot 2023-05-26 at 10 55 13 PM" src="https://github.com/jaydenseric/graphql-upload/assets/37369204/9072c2c4-4eb9-490d-b6a9-502eb477b608">

and here is what it looks like after update
<img width="461" alt="Screenshot 2023-05-26 at 10 55 37 PM" src="https://github.com/jaydenseric/graphql-upload/assets/37369204/b50aa7ce-649f-4544-b188-cee92b3a4022">

the one thing which I wanted to do (and did) was to remove this ""preinstall": "npx npm-force-resolutions","

please let me know how I can resolve this error

**Comment by jaydenseric** [comment]
Hi @aoneahsan , the error is because you can no longer import from a main module at `"graphql-upload"`; you need to specify exactly the module you want to import. E.g:

```js
import graphqlUploadExpress from "grpahql-upload/graphqlUploadExpress.mjs";
```

You can see all the modules you can import here:

https://github.com/jaydenseric/graphql-upload/tree/v16.0.2#exports

This is for [optimal JavaScript module design](https://jaydenseric.com/blog/optimal-javascript-module-design).

These breaking changes about how modules can be imported have been documented in the changelog and GitHub releases for each of the major version you are upgrading past, including migration examples for each of the imports:

- https://github.com/jaydenseric/graphql-upload/blob/v16.0.2/changelog.md
- https://github.com/jaydenseric/graphql-upload/releases
