### ISSUE TITLE
 Invalid object path for the 'map' multipart field entry key '0' array index '0' 

### ISSUE THREAD

**Issue by Eriickson** [jaydenseric/graphql-upload#375]
<img width="1824" alt="Screenshot 2023-07-13 at 4 21 54 AM" src="https://github.com/jaydenseric/graphql-upload/assets/38663299/b479b23f-300b-46af-aff2-e9c8a72ae0bd">
<img width="633" alt="Screenshot 2023-07-13 at 4 22 38 AM" src="https://github.com/jaydenseric/graphql-upload/assets/38663299/380a174d-8dd3-4112-b5d7-63cb125a1903">

<img width="995" alt="Screenshot 2023-07-13 at 4 22 56 AM" src="https://github.com/jaydenseric/graphql-upload/assets/38663299/d05be0d0-68e0-4b5a-813d-e4b49ea87ab8">

**Comment by jaydenseric** [comment]
This issue is not an actionable bug report for `graphql-upload`.

To debug this problem in your project, I suggest using the browser network inspector to check the GraphQL request body, and see how that the parts mentioned in the error message is not correct for a GraphQL multipart request:

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure
