### ISSUE TITLE
upload multiple images has error

### ISSUE THREAD

**Issue by hajmansoor** [jaydenseric/graphql-upload#384]
When I want to upload multiple images only the first file has "file" content and the other file does not have file content(only file with extension .png .xls . )
file with txt format worked fine
![image](https://github.com/jaydenseric/graphql-upload/assets/156500929/7daff0f6-c101-4330-8b61-d407e56a5e9d)

please help me

**Comment by jaydenseric** [comment]
It's not clear why you are accessing the `Upload` instances directly; if everything is setup correctly with the scalar `GraphQLUpload` you won't see that in resolvers; only you can access the upload promise. You need to properly await the upload promise, then use that to create and promisify a readable stream for the upload, and then await the completion of the stream. You have to do something with the upload stream, even if you just waste it, otherwise the later file upload promises will never resolve and they will never start streaming. Streams of files in multipart requests are received one after another, not in parallel.
